name: SonarQube Python Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sonarQube:
    name: SonarQube Scan
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3
      
      # Set up Python
      - name: Set up Python 3.11.0
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      
      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Run SonarQube analysis
      - name: Run SonarQube analysis
        uses: SonarSource/sonarcloud-github-action@v1.5
        with:
          sonar-token: ${{ sqa_e80b25b6c0685599c12afcf17ee8767ad4463d38 }}
          sonar-host-url: ${{http://localhost:9000 }}
